version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: multi_asset_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "52098:5432"
    restart: always

  app:
    build: .
    container_name: Multi-Asset-Signal-Engine
    ports:
      - "41923:5000"
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/multi_asset_db
      NODE_ENV: production
      PORT: 5000
    depends_on:
      - db
    restart: always

volumes:
  pgdata:
